import XLSX from 'xlsx';
import path from 'node:path';
import fs from 'node:fs';

const file = path.resolve(process.cwd(), '..', 'PIT_Summary_Report_Template.xlsx');
const wb = XLSX.readFile(file, { cellStyles: true, sheetStubs: true });

const dne = wb.Sheets['DO_NOT_EDIT'];
const rows = XLSX.utils.sheet_to_json(dne, { header: 1, defval: null, raw: false, blankrows: false });

// Variable list starts at row 17 (index 16). col A = name, col E = which sheet uses it
const all = [];
for (let i = 16; i < rows.length; i++) {
  const name = rows[i]?.[0];
  const page = rows[i]?.[4] ?? '';
  if (!name) continue;
  all.push({ name, page });
}

const unsheltered = all.filter((v) => /Unsheltered/i.test(v.name) || /UnshelteredVet/i.test(v.name));
const metadata = all.filter((v) => v.page === 'MetadataFIeld');

console.log(`Total variables: ${all.length}`);
console.log(`Metadata variables: ${metadata.length}`);
console.log(`Unsheltered variables: ${unsheltered.length}`);

const byPage = {};
for (const v of unsheltered) {
  (byPage[v.page] ??= []).push(v.name);
}

console.log('\n=== Unsheltered variables by page ===');
for (const [page, names] of Object.entries(byPage)) {
  console.log(`\n${page} (${names.length}):`);
  for (const n of names) console.log(`  ${n}`);
}

// Emit JSON
const out = { metadata: metadata.map((v) => v.name), unsheltered: byPage };
fs.writeFileSync(
  path.resolve(process.cwd(), 'scripts', 'pit-variables.json'),
  JSON.stringify(out, null, 2),
);
console.log(`\nWrote pit-variables.json`);

// Emit TS module — full ordered list of every variable in the template so the
// writer can write all 650 cells (Unsheltered filled, Sheltered left blank).
const tsLines = [];
tsLines.push('// AUTO-GENERATED by scripts/extract-vars.mjs from PIT_Summary_Report_Template.xlsx');
tsLines.push('// Re-run that script after any HUD template update.');
tsLines.push('');
tsLines.push('export const ALL_PIT_VARIABLES: readonly string[] = [');
for (const v of all) tsLines.push(`  ${JSON.stringify(v.name)},`);
tsLines.push('];');
tsLines.push('');
tsLines.push('export const UNSHELTERED_VARIABLES: readonly string[] = [');
for (const v of unsheltered) tsLines.push(`  ${JSON.stringify(v.name)},`);
tsLines.push('];');
tsLines.push('');
tsLines.push('export const METADATA_VARIABLES: readonly string[] = [');
for (const v of metadata) tsLines.push(`  ${JSON.stringify(v.name)},`);
tsLines.push('];');
tsLines.push('');

const tsOut = path.resolve(process.cwd(), 'src', 'lib', 'exports', 'pitVariables.generated.ts');
fs.mkdirSync(path.dirname(tsOut), { recursive: true });
fs.writeFileSync(tsOut, tsLines.join('\n'));
console.log(`Wrote ${tsOut}`);
